Nostr feeds support
spacecowboy/Feeder pull request #471
Opened 2024-12-26 22:36 UTC by KotlinGeekDev

This PR adds support for using the [Nostr protocol](https://github.com/nostr-protocol/nostr), specifically the [long form content](https://github.com/nostr-protocol/nips/blob/master/23.md) part of the specifications, and to support using [Nostr URIs](https://github.com/nostr-protocol/nips/blob/master/21.md) as a way to fetch the feed of a particular person.
The PR also adds support for identifying Nostr URIs in OPML files when importing them.
A demo of how this integration works is shown below:

https://github.com/user-attachments/assets/db9852b6-86f4-423f-84f4-bc6890a3a8d1

Thank you for your work.

2024-12-27 15:00 UTC, spacecowboy commented
Looks very interesting. Thanks for contributing!

I'll take a closer look as soon as I'm back at a proper screen.

2024-12-27 18:41 UTC, KotlinGeekDev commented
> Looks very interesting. Thanks for contributing!
> 
> I'll take a closer look as soon as I'm back at a proper screen.

Thank you for looking into this. I hope the code will not have many issues for you.

2025-01-01 15:39 UTC, spacecowboy requested changes
Sorry for the delay. I've added some comments. Gonna build it and try it also

2025-01-01 15:39 UTC, spacecowboy commented on app/build.gradle.kts
> +    implementation("org.jetbrains:markdown:0.7.3")
Should move this to the dependency catalog in `settings.gradle.kts`

2025-01-01 15:39 UTC, spacecowboy commented on app/build.gradle.kts
> +            matchingFallbacks.add("release")
:+1:

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                else -> throw Throwable(message = "Could not find the user's info: $nostrUri")
You should never throw a `Throwable` directly. Throw a real exception instead.

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +            println("Relays from Nip19 -> ${relayList.joinToString(separator = ", ")}")
```suggestion
```

Remove all `println`

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +            println(profileInfo.asPrettyJson())
```suggestion
```

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +        logDebug(LOG_TAG, "Relay List size: -> ${relays.size}")
```suggestion
        logDebug(LOG_TAG, "Relay List size: ${relays.size}")
```

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +        logDebug(LOG_TAG, "-------------------FETCHING ARTICLES----------------------")
```suggestion
        logDebug(LOG_TAG, "FETCHING ARTICLES")
```

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +    val description = "Nostr articles by $authorName"
Is this string user visible? If so it should not be hardcoded in english

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +    val htmlFromContent = HtmlGenerator(articleContent, parsedMarkdown, CommonMarkFlavourDescriptor()).generateHtml()
```suggestion
    val htmlContent = HtmlGenerator(articleContent, parsedMarkdown, CommonMarkFlavourDescriptor()).generateHtml()
```

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +        content_html = htmlFromContent,
```suggestion
        content_html = htmlContent,
```

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                else -> throw Throwable(message = "Could not find the user's info: $nostrUri")
See `FetchError` for example

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.kt
> +                    .getOrNull()!!
Please don't throw a null pointer exception here

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OPMLImporter.kt
> +        val existingNostrFeeds = feedDao.getAllFeeds().filter { it.url.isAdaptedUrlFromNostrUri() }
Don't load all feeds here for every feed.

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OPMLImporter.kt
> +                val potentialNostrFeed = existingNostrFeeds.find { it.title == feed.title }
I don't think this is a very good idea. Feed titles are not unique.

If a user wants to add a second copy of a feed with a different url, then let them.

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OpmlPullParser.kt
> +                            } else {
```suggestion
```

Remove this. You should respect the values in the file

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/CreateFeedScreenViewModel.kt
> +    // These three are updated as a result of url/uri updating
Thanks for updating comment

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/CreateFeedScreenViewModel.kt
> +                        fullTextByDefault = if (isNostrUri) false else fullTextByDefault,
```suggestion
                        fullTextByDefault = fullTextByDefault,
```

Again. Do not override user's choices

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +        isError = !viewState.isNostrUri && viewState.isNotValidUrl,
Could you please move the `isNostrUri` logic inside `isValidUrl` function instead?

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +    AnimatedVisibility(visible = !viewState.isNostrUri && viewState.isNotValidUrl) {
Move inside `isNotValidUrl`

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +        checked = if (viewState.isNostrUri) false else viewState.fullTextByDefault,
```suggestion
        checked = viewState.fullTextByDefault,
```

Do not override

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +            (isValidUrl(feedUrl) || feedUrl.isNostrUri())
move inside isvalid

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +                    if (feedUrl.isNostrUri()) "https://njump.me/$feedUrl" else feedUrl,
`if (feedUrl.isNostrUri()) "https://njump.me/$feedUrl" else feedUrl` is repeated enough times that it should be moved to a simple getter

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +        isError = isNotValidUrl && !isNostrUri,
move inside

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +                    if (isValidUrl || isNostrUri) {
move inside

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +//                        }
Left over comment?

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +                            description = "Nostr Articles by ${metadata.name}",
Is this user visible? If so should not be hard coded english

2025-01-01 15:39 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/util/LinkUtils.kt
> +    val nostrPrefix = "nostr:"
This should be moved to a constant

2025-01-01 19:04 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OPMLImporter.kt
> +                val potentialNostrFeed = existingNostrFeeds.find { it.title == feed.title }
OK, will fix.

2025-01-01 19:07 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OpmlPullParser.kt
> +                            } else {
Please @spacecowboy  actually for Nostr sources, the full text option is not needed because the full article is fetched regardless, and I have not seen how to adapt that option to Nostr sources.

2025-01-01 19:08 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/CreateFeedScreenViewModel.kt
> +                        fullTextByDefault = if (isNostrUri) false else fullTextByDefault,
The comment for the OPMLPullParser code applies here as well.

2025-01-01 19:08 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +        isError = !viewState.isNostrUri && viewState.isNotValidUrl,
Will fix.

2025-01-01 19:12 UTC, KotlinGeekDev commented
Thanks for the review! Please, I left some comments above about the rationale for some choices in the code.
Perhaps we can find another way to fix them.
Thank you.

2025-01-02 10:18 UTC, KotlinGeekDev commented on app/build.gradle.kts
> +    implementation("org.jetbrains:markdown:0.7.3")
Fixed.

2025-01-02 10:36 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                else -> throw Throwable(message = "Could not find the user's info: $nostrUri")
> You should never throw a `Throwable` directly. Throw a real exception instead.

I could create a particular 'NostrUriParserException' for this.

2025-01-02 10:44 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +            println(profileInfo.asPrettyJson())
I think I will change all the `println` to `logDebug`, as they might be very useful.

2025-01-02 12:03 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +//                        }
Forgot about that. Will fix.

2025-01-02 13:16 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/util/LinkUtils.kt
> +    val nostrPrefix = "nostr:"
Fixed.

2025-01-02 13:16 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +                            description = "Nostr Articles by ${metadata.name}",
Fixed.

2025-01-02 13:16 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +//                        }
Fixed.

2025-01-02 13:17 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +                    if (isValidUrl || isNostrUri) {
Fixed.

2025-01-02 13:17 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +        isError = isNotValidUrl && !isNostrUri,
Fixed.

2025-01-02 13:18 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedScreen.kt
> +            (isValidUrl(feedUrl) || feedUrl.isNostrUri())
Done.

2025-01-02 13:18 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +        checked = if (viewState.isNostrUri) false else viewState.fullTextByDefault,
Fixed.

2025-01-02 13:18 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +    AnimatedVisibility(visible = !viewState.isNostrUri && viewState.isNotValidUrl) {
Done.

2025-01-02 13:19 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/editfeed/EditFeedScreen.kt
> +        isError = !viewState.isNostrUri && viewState.isNotValidUrl,
Fixed.

2025-01-02 13:20 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OPMLImporter.kt
> +                val potentialNostrFeed = existingNostrFeeds.find { it.title == feed.title }
Fixed.

2025-01-02 13:20 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/opml/OPMLImporter.kt
> +        val existingNostrFeeds = feedDao.getAllFeeds().filter { it.url.isAdaptedUrlFromNostrUri() }
Fixed.

2025-01-02 13:20 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.kt
> +                    .getOrNull()!!
Fixed.

2025-01-02 13:21 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +    val description = "Nostr articles by $authorName"
Fixed.

2025-01-02 13:23 UTC, KotlinGeekDev commented
Also, please @spacecowboy here is an OPML file you can use to try out: https://github.com/fiatjaf/narr/blob/master/etc/promo.opml

2025-01-02 18:48 UTC, spacecowboy commented
I suggest that you do not rename string resources. You'll get constant conflicts with translations

2025-01-02 18:57 UTC, spacecowboy commented
and on that theme, don't change the string to `url/uri`. Regular users have no idea what the difference is

2025-01-02 19:51 UTC, KotlinGeekDev commented
> and on that theme, don't change the string to `url/uri`. Regular users have no idea what the difference is

Got it. Let me fix that.

2025-01-02 20:02 UTC, KotlinGeekDev commented
Everything is fixed now.

2025-01-02 23:56 UTC, spacecowboy requested changes
Nice work.

Found some issues in my tests, I've added suggested changes above.

Also two general questions about number of relays used.

2025-01-02 23:56 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                    }.orEmpty()
Why are you only using the list if it has less than 4 relays?

2025-01-02 23:56 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                .ifEmpty { defaultFetchRelays }
and here, is there a specific reason for taking up to 2 and a random other relay?

2025-01-02 23:56 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.kt
> +    private val application: FeederApplication by instance()
This caused a crash in my tests.
```suggestion
    private val application: Application by instance()
```

2025-01-02 23:56 UTC, spacecowboy commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +    private val application: FeederApplication by instance()
```suggestion
    private val application: Application by instance()
```

This caused a crash in my tests

2025-01-03 07:26 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.kt
> +    private val application: FeederApplication by instance()
Interesting. Will fix that.

2025-01-03 07:28 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                    }.orEmpty()
Generally, connecting to a big number of relays takes more in terms of time and bandwidth. And since we are just fetching the author's information, it should not take long, and 3 relays are more than enough for that.

2025-01-03 07:32 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/FeedParser.kt
> +                .ifEmpty { defaultFetchRelays }
I should probably bump the number to 3 relays, but the reasoning here is similar to the one above, and even more so because the author can have a large number of articles, and connecting to many relays will worsen the fetch time. There's an author who had 272 articles, and it took about 40s to fetch them!

2025-01-03 09:56 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/ui/compose/searchfeed/SearchFeedViewModel.kt
> +    private val application: FeederApplication by instance()
Fixed.

2025-01-03 09:56 UTC, KotlinGeekDev commented on app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.kt
> +    private val application: FeederApplication by instance()
Fixed.

2025-01-03 10:08 UTC, KotlinGeekDev commented
Thanks for the review. I answered the questions and made the necessary fixes.

2025-01-04 00:56 UTC, KotlinGeekDev commented
Everything is now alright, @spacecowboy .

2025-01-04 01:05 UTC, spacecowboy approved these changes

2025-01-04 01:05 UTC, spacecowboy commented
Thank you @KotlinGeekDev . I think it's allright to merge now

2025-01-04 01:06 UTC, merged

2025-01-04 10:57 UTC, KotlinGeekDev commented
> Thank you @KotlinGeekDev . I think it's allright to merge now

Thank you @spacecowboy for taking the time to review the PR and merge it,
and thanks for your work on Feeder! :pray: